name: x86_64-posix-seh-ucrt

on:
  workflow_dispatch:

env:
  MINGW_BUILDS_GCC_VERSION: "16.2.0"
  MINGW_BUILDS_RT_VERSION: "v14"

jobs:
  download:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: gettext

    - name: Patch script to enable NLS
      shell: msys2 {0}
      run: sed -i 's/--disable-nls/--enable-nls/g' scripts/gcc-$MINGW_BUILDS_GCC_VERSION.sh

    - name: 下载源文件
      shell: msys2 {0}
      run: >-
        ./build
        --mode=gcc-$MINGW_BUILDS_GCC_VERSION
        --buildroot=/c/buildroot
        --jobs=4
        --rev=0
        --with-default-msvcrt=ucrt
        --rt-version=$MINGW_BUILDS_RT_VERSION
        --threads=mcf
        --exceptions=seh
        --arch=x86_64
        --bin-compress
        --enable-languages=c,c++
        --logviewer-command=cat
        --fetch-only

    - name: 压缩源文件
      run: 7z a src.7z src "-xr!.git"
      working-directory: c:/buildroot

    - name: 上传源文件
      uses: actions/upload-artifact@v7
      with:
        path: c:/buildroot/src.7z
        compression-level: 0
        archive: false

  build:
    name: x86_64-posix-seh-ucrt
    runs-on: windows-latest
    needs: download
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v7

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: gettext

    - name: Patch script to enable NLS
      shell: msys2 {0}
      run: sed -i 's/--disable-nls/--enable-nls/g' scripts/gcc-$MINGW_BUILDS_GCC_VERSION.sh

    - name: 下载源文件
      uses: actions/download-artifact@v8
      with:
        name: src.7z
        path: c:/buildroot

    - name: 解压源文件
      run: 7z x src.7z
      working-directory: c:/buildroot

    - name: 构建
      shell: msys2 {0}
      run: >-
        ./build
        --mode=gcc-$MINGW_BUILDS_GCC_VERSION
        --buildroot=/c/buildroot
        --jobs=4
        --rev=0
        --with-default-msvcrt=ucrt
        --rt-version=$MINGW_BUILDS_RT_VERSION
        --threads=posix
        --exceptions=seh
        --arch=x86_64
        --bin-compress
        --enable-languages=c,c++
        --logviewer-command=cat

    - name: 上传
      uses: actions/upload-artifact@v7
      with:
        name: bin-x86_64-posix-seh-ucrt
        path: c:/buildroot/archives/

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v8
      with:
        pattern: "bin-*"
        path: ./
        merge-multiple: true

    - name: Upload to Release
      id: upload_to_release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.7z"
